import { PlatformType, PresetConfiguration } from '../types/calculator';

export const PLATFORM_PRESETS: Record<PlatformType, PresetConfiguration> = {
  youtube: {
    id: 'youtube',
    label: 'YouTube Video',
    description: 'Long-form videos, tutorials, tech reviews, video essays, and documentary content.',
    defaultWpm: 155,
    defaultPacePreset: 'standard',
    defaultIntroSeconds: 15,
    defaultOutroSeconds: 20,
    defaultPausePercentage: 10,
    defaultAdBreakDurationSeconds: 60,
    defaultNumberOfAdBreaks: 1,
    defaultBRollPercentage: 40,
    defaultAverageSceneDurationSeconds: 4.8,
    defaultAverageBRollClipDurationSeconds: 3.2,
    recommendedPaceRange: { min: 140, max: 175 },
    tip: 'YouTube retention drops when shots remain static for more than 5 seconds. Target 40-50% B-roll with cuts every 3-5 seconds.',
    sampleScript: `Welcome back to Tech Horizon. Today, we're dissecting the next generation of mirrorless cameras and why sensor stabilization is changing documentary production.

Over the past three months, our team tested five leading cameras in low-light environments, run-and-gun street scenes, and controlled studio settings. What we discovered challenged our assumptions about megapixel counts and dynamic range.

Before we inspect the test footage, make sure to hit the subscribe button and drop your current camera rig down in the comments. Now, let's look at the sensor readout speed.`,
  },
  tiktok: {
    id: 'tiktok',
    label: 'TikTok',
    description: 'Fast-paced, hook-driven short-form vertical video under 60-90 seconds.',
    defaultWpm: 185,
    defaultPacePreset: 'fast',
    defaultIntroSeconds: 2,
    defaultOutroSeconds: 3,
    defaultPausePercentage: 4,
    defaultAdBreakDurationSeconds: 0,
    defaultNumberOfAdBreaks: 0,
    defaultBRollPercentage: 55,
    defaultAverageSceneDurationSeconds: 2.2,
    defaultAverageBRollClipDurationSeconds: 1.8,
    recommendedPaceRange: { min: 170, max: 210 },
    tip: 'First 2 seconds determine 80% of retention. Cut every pause and jump-cut between key phrases.',
    sampleScript: `Stop scrolling! If you're still editing videos the old way, you're wasting three hours every single week. Here are three automated shortcuts you need right now. Number one: ripple edits with single keystrokes. Number two: auto-transcription for instant captions. And number three: batch export presets. Save this video so you don't forget!`,
  },
  instagram_reel: {
    id: 'instagram_reel',
    label: 'Instagram Reel',
    description: 'Aesthetic, punchy vertical reels with high visual variety and trending pacing.',
    defaultWpm: 175,
    defaultPacePreset: 'fast',
    defaultIntroSeconds: 3,
    defaultOutroSeconds: 4,
    defaultPausePercentage: 6,
    defaultAdBreakDurationSeconds: 0,
    defaultNumberOfAdBreaks: 0,
    defaultBRollPercentage: 50,
    defaultAverageSceneDurationSeconds: 2.5,
    defaultAverageBRollClipDurationSeconds: 2.0,
    recommendedPaceRange: { min: 160, max: 195 },
    tip: 'Pair dynamic voice-over delivery with visually stimulating on-screen motion graphics.',
    sampleScript: `Here is the exact framework I used to grow our creator business without burning out. We shifted from daily posting to two deeply researched high-value breakdowns each week. The result? 40% higher saves and 3x more comments. Link in bio for the complete template.`,
  },
  podcast: {
    id: 'podcast',
    label: 'Podcast Episode',
    description: 'Audio-first discussions, interviews, conversational storytelling, and audiobooks.',
    defaultWpm: 140,
    defaultPacePreset: 'conversational',
    defaultIntroSeconds: 30,
    defaultOutroSeconds: 45,
    defaultPausePercentage: 14,
    defaultAdBreakDurationSeconds: 45,
    defaultNumberOfAdBreaks: 2,
    defaultBRollPercentage: 0,
    defaultAverageSceneDurationSeconds: 20,
    defaultAverageBRollClipDurationSeconds: 5.0,
    recommendedPaceRange: { min: 130, max: 155 },
    tip: 'Audio listeners need breathing room. Natural pauses allow complex ideas to land and avoid cognitive fatigue.',
    sampleScript: `Hello and welcome back to the Creative Mind podcast. I'm your host, and today we're joined by an extraordinary guest who spent the last decade building independent media companies.

In this episode, we're discussing how independent writers transition to multi-format video production, how to navigate creative burnout, and the practical economics of modern sponsorships.

Take a breath, grab your favorite drink, and let's jump straight into the conversation.`,
  },
  voice_over: {
    id: 'voice_over',
    label: 'Commercial Voice-Over',
    description: 'Commercials, explainer animations, e-learning modules, and corporate narrations.',
    defaultWpm: 150,
    defaultPacePreset: 'standard',
    defaultIntroSeconds: 0,
    defaultOutroSeconds: 0,
    defaultPausePercentage: 8,
    defaultAdBreakDurationSeconds: 0,
    defaultNumberOfAdBreaks: 0,
    defaultBRollPercentage: 0,
    defaultAverageSceneDurationSeconds: 5,
    defaultAverageBRollClipDurationSeconds: 3.0,
    recommendedPaceRange: { min: 140, max: 160 },
    tip: 'Commercials demand strict timing constraints (15s, 30s, 60s spots). Measure word count precisely to prevent rushed vocal delivery.',
    sampleScript: `In a world of constant digital distraction, clarity is your ultimate competitive advantage. Introducing Lumina Studio: seamless collaboration engineered specifically for distributed creative teams. Work together in real time, finalize assets in half the time, and ship your best work yet. Try Lumina free today.`,
  },
  presentation: {
    id: 'presentation',
    label: 'Slide Presentation',
    description: 'Keynotes, webinar pitch decks, company all-hands, and investor presentations.',
    defaultWpm: 130,
    defaultPacePreset: 'slow',
    defaultIntroSeconds: 20,
    defaultOutroSeconds: 60,
    defaultPausePercentage: 16,
    defaultAdBreakDurationSeconds: 0,
    defaultNumberOfAdBreaks: 0,
    defaultBRollPercentage: 20,
    defaultAverageSceneDurationSeconds: 25,
    defaultAverageBRollClipDurationSeconds: 4.0,
    recommendedPaceRange: { min: 120, max: 145 },
    tip: 'Rule of thumb: allow 1.5 to 2.5 minutes per slide. Pause deliberately after revealing critical data points.',
    sampleScript: `Good morning, everyone. Thank you for taking the time to join our annual strategy overview.

Over the next thirty minutes, we will examine our core financial milestones from the past year, review our customer retention metrics, and outline our three strategic pillars for the coming quarter.

Please hold your questions until the end where we have reserved twenty minutes dedicated to discussion. Let us start with slide three.`,
  },
  speech: {
    id: 'speech',
    label: 'Public Speech & Keynote',
    description: 'Commencement addresses, wedding toasts, award acceptance speeches, and conference keynotes.',
    defaultWpm: 120,
    defaultPacePreset: 'slow',
    defaultIntroSeconds: 15,
    defaultOutroSeconds: 30,
    defaultPausePercentage: 20,
    defaultAdBreakDurationSeconds: 0,
    defaultNumberOfAdBreaks: 0,
    defaultBRollPercentage: 0,
    defaultAverageSceneDurationSeconds: 30,
    defaultAverageBRollClipDurationSeconds: 5.0,
    recommendedPaceRange: { min: 105, max: 135 },
    tip: 'Speeches require longer rhetorical pauses (2-3 seconds) for audience reaction, laughter, and emotional weight.',
    sampleScript: `Distinguished guests, faculty, and fellow graduates: today is not merely the end of an academic chapter; it is the beginning of a profound responsibility.

When we first walked through these gates, we held doubts about our ability to shape the future. Today, looking across this auditorium, I do not see doubt. I see conviction, resilience, and boundless possibility. Let us remember that true success is measured not by individual accolades, but by the doors we open for those who follow.`,
  },
  custom: {
    id: 'custom',
    label: 'Custom Production',
    description: 'Fully customizable parameters for television broadcast, documentary films, or bespoke formats.',
    defaultWpm: 150,
    defaultPacePreset: 'custom',
    defaultIntroSeconds: 10,
    defaultOutroSeconds: 15,
    defaultPausePercentage: 10,
    defaultAdBreakDurationSeconds: 30,
    defaultNumberOfAdBreaks: 1,
    defaultBRollPercentage: 35,
    defaultAverageSceneDurationSeconds: 5.0,
    defaultAverageBRollClipDurationSeconds: 3.0,
    recommendedPaceRange: { min: 80, max: 250 },
    tip: 'Configure each variable according to your specific storyboard and post-production plan.',
    sampleScript: `This is a sample script configured for customized production analysis. Paste your bespoke text here to inspect scene cuts, speaking duration, B-roll density, and word count.`,
  },
};
